/* AUTOGENERATED FILE - DO NOT EDIT CONTENTS */

export const projectId = "mzvpbrndzeorcfvgnaqe"
export const publicAnonKey = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im16dnBicm5kemVvcmNmdmduYXFlIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NjI2MTczODEsImV4cCI6MjA3ODE5MzM4MX0.t0-BjkRyagoN6hAA6Ue6v-POiuqVgyjXKenAEM7d2wY"